### ISSUE TITLE
i assume this dont work if it does pls send

### ISSUE THREAD

**Issue by Priest6942000** [alexlostorto/magic-notes#15]
i assume this dont work if it does pls send

**Comment by alexlostorto** [comment]
I will not be updating the magic notes extension since I don't use Sparx
anymore (and i dont have an account) but thanks for the enquiry.

Hopefully someone else will fix it on my behalf (it would just require
changing the element selectors to the new website design).

**Comment by c0lide** [comment]
New, updated and Feature-rich [SparxSolver](https://github.com/c0lide/sparxsolver/releases) Extension
