### ISSUE TITLE
Not working on MS Edge

### ISSUE THREAD

**Issue by GloriousGlider8** [alexlostorto/magic-notes#16]
The extension does not work on Microsoft Edge.

**Comment by alexlostorto** [comment]
It doesn't work at all after Sparx's recent redesign 💀

**Comment by Pottle** [comment]
Do you have any plans to update it?

**Comment by alexlostorto** [comment]
https://github.com/alexlostorto/magic-notes/issues/15

**Comment by c0lide** [comment]
New, updated and Feature-rich [SparxSolver](https://github.com/c0lide/sparxsolver/releases) Extension

**Comment by alexlostorto** [comment]
Very cool, who wrote it and how?

**Comment by c0lide** [comment]
https://github.com/acquitelol/azalea
Typescript
