### ISSUE TITLE
the chrome extension doesn't work

### ISSUE THREAD

**Issue by lizrce** [alexlostorto/magic-notes#17]
Hi! So I wanted to use Magic Notes because I couldn't be bothered to do bookwork checks, but for some reason, the temporary version and the chrome extension both do not work for me. I followed the instructions clearly and it still didn't work. It's probably just me, but it would be nice if the issue was fixed. 

Thanks!

**Comment by h0sm** [comment]
Heya @lizrce !

The extension will no longer function as Sparx Maths has remodeled their site. The projects continuance relies on the creator of Magic Notes who is in exams. Hopefully this will clear up some of your confusions (and frustrations)

**Comment by alexlostorto** [comment]
Tysm @hosm100 for the message. You can click [here ](https://github.com/alexlostorto/magic-notes/issues/15) to view a previous issue on this matter.

You know you've made it somewhere if people are going out of their way to reply on your behalf 😅

**Comment by lizrce** [comment]
> Heya @lizrce !
> 
> The extension will no longer function as Sparx Maths has remodeled their site. The projects continuance relies on the creator of Magic Notes who is in exams. Hopefully this will clear up some of your confusions (and frustrations)

Oh my gosh! I'm really really sorry, I'm a bit dumb sometimes, but yea I'm really sorry about this😭. I won't cause anymore disturbances. Thank you so much!!

**Comment by c0lide** [comment]
New, updated and Feature-rich [SparxSolver](https://github.com/c0lide/sparxsolver/releases) Extension
