### ISSUE TITLE
.

### ISSUE THREAD

**Issue by NajmAjmal** [alexlostorto/magic-notes#18]

**Comment by alexlostorto** [comment]
Hey Najm,

Thanks for coming to me about this. I did NOT do this and have NO knowledge regarding who did this.

I don't condemn using my name like this, nor do I condemn hacking others without their prior permission.

Hope this helps,

Alex

**Comment by NajmAjmal** [comment]
Thanks, Alex

Anyone can put anyone's name on anything, whether it's good or bad.

**Comment by alexlostorto** [comment]
Exactly.
