### ISSUE TITLE
Please firefox support.

### ISSUE THREAD

**Issue by Schsmci** [alexlostorto/magic-notes#5]
Hi, I hope this project keeps on going on. Is there anyway you can make the extension supported for firefox.

**Comment by alexlostorto** [comment]
The console script is written in vanilla javascript, so theoretically, it should work just fine in Firefox. Just open developer tools (the shortcut might be different on Firefox) and paste the code.

Instructions on how to use the console script are below :)

_PS: I will no longer be maintaining this project, if Sparx patches any vulnerabilities or restructures their website (which they will probably do sometime soon) the program will no longer work._

## ⚡ Quick setup

1. Visit [**Magic Notes**](https://alexlostorto.github.io/magic-notes/) and scroll down to click the _Copy_ button.
2. Log in to Sparx Maths and open the **Developers Console** with _Ctrl + Shift + J_
3. Paste the code in the Console and press _Enter_.
4. Star the repo 😄
